name: Publish PyPI Release

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Build & Publish Wheel to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          pip install build twine wheel

      - name: Build Source Distribution and Wheel
        run: |
          python -m build

      - name: Publish Package to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
